### ISSUE TITLE
Restore stanza-with-visualization?

### ISSUE THREAD

**Issue by bollwyvl** [conda-forge/stanza-feedstock#26]
### Comment:

On https://github.com/conda-forge/stanza-feedstock/pull/25, it appears that the `visualization` extra runs afoul of `blis`, `streamlit`, `numpy` and `protobuf`.

As there don't appear to be any references outside of the feedstock, going to remove it. It should be re-added in the future (perhaps after https://github.com/conda-forge/blis-feedstock/pull/33)

**Comment by AngledLuffa** [comment]
Anything in particular going wrong that we can fix?

**Comment by bollwyvl** [comment]
#28

**Comment by bollwyvl** [comment]
Shipped, but should revisit after:
https://github.com/conda-forge/cython-blis-feedstock/pull/60
